name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@main
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: create .env
      run: 
        echo 'DB_NAME=${{secrets.DB_NAME}}' >> .env
        echo 'DB_USER=${{secrets.DB_USER}}' >> .env
        echo 'DB_PASSWORD=${{secrets.DB_PASSWORD}}' >> .env
        echo 'DB_ROOT_PASSWORD=${{secrets.DB_ROOT_PASSWORD}}' >> .env
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker
      run: docker compose up --build -d 


